export const primary = '#00F0C7';
export const secondary = '#927DFE';
export const warning = '#F63B3B';
export const gradient = ['#00F0C7', '#927DFE'];
export const white = '#FFF';
export const gray = '#7E7E7E';
export const grey = '#E7E7E7';
export const blackGrey = '#D1D1D1';
export const black = '#282F37';
export const blackOpacity = 'rgba(0, 0, 0, .5)'